### ISSUE TITLE
Do not mix tabs and spaces

### ISSUE THREAD

**Issue by langpavel** [daniellmb/React-PE#1]
Please do not mix tabs and spaces. Code is hard readable.
Add `.editorconfig` and/or setup your IDE

**Comment by daniellmb** [comment]
Agreed, I was using Visual Studio for the project and it don't support `.editorconfig` or jsx syntax out of the box yet. +1 for [WebStorm](http://blog.jetbrains.com/webstorm/2014/10/webstorm-9-released-meteor-support-react-and-jsx-gulp-integration-and-more/) :)
